name: Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels:
  - bug

body:
  - type: input
    id: Bug-Describe
    attributes:
      label: Describe the bug
      placeholder: 'A clear and concise description of the error in one sentence.'
    validations:
      required: true
        
  - type: textarea
    id: Reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        If applicable, add screenshots to help explain your problem.

        Provide steps to reproduce the behavior. eg:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
        
  - type: textarea
    id: Expected-Behavior
    attributes:
      label: Expected behavior
      placeholder: 'A clear and concise description of what you expected to happen.'
    validations:
      required: true

  - type: textarea
    id: App-Info
    attributes:
      label: App Info 
      placeholder: 'You can copy app info from the "About" page in the app.'
    validations:
      required: true

  - type: textarea
    id: Additional-Context
    attributes:
      label: Additional context
      placeholder: 'Add any other context about the problem here.'

  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report."